### ISSUE TITLE
string-format.js doesn't work on jsfiddle

### ISSUE THREAD

**Issue by madhavan020985** [davidchambers/string-format#11]
My jsfiddle link is at,
````
http://jsfiddle.net/ud92x01d/
````
In the console, i can see it throws error as,

Uncaught TypeError: Cannot set property 'format' of undefined at line number 94

I can fix it by changing ln94 from global.format to window.format, though

**Comment by davidchambers** [comment]
Thanks very much for the bug report, @madhavan020985. This regression was introduced by the recent CoffeeScript → JavaScript rewrite. It's now fixed on __master__.
