### ISSUE TITLE
Regular Error when golang run js vm with this module

### ISSUE THREAD

**Issue by 3dseals** [davidchambers/string-format#17]
hello, i got a Regular Error : JsScript: (anonymous): Line 36:31 Invalid regular expression: re2: Invalid \1. when running on my golang js vm.
original:
`/([{}])\1|[{](.*?)(?:!(.+?))?[}]/`
Suggest:
`/([{}])\\1|[{](.*?)(?:!(.+?))?[}]/`

**Comment by davidchambers** [comment]
Your suggested change would not work. `([{}])\1` matches `'{{'` and `'}}'`; `([{}])\\1` matches `'{\\1'` and `'}\\1'`.

```javascript
> /([{}])\1/.test('{{')
true
> /([{}])\1/.test('}}')
true
> /([{}])\\1/.test('{{')
false
> /([{}])\\1/.test('}}')
false
> /([{}])\\1/.test('{\\1')
true
> /([{}])\\1/.test('}\\1')
true
```

It sounds to me as though the problem lies elsewhere, so I'll close this issue. Feel free to comment if you have more information.

**Comment by rognoni** [comment]
@3dseals try to check your regex here https://regex101.com/
