### ISSUE TITLE
Bower support?

### ISSUE THREAD

**Issue by joseangeljimenez** [davidchambers/string-format#18]
Just a suggestion. It'll be great if you could provide bower support.
Otherwise, thanks a lot for this great utility library.

**Comment by davidchambers** [comment]
Good idea, @joseangeljimenez. I'll open a pull request to add __bower.json__.

**Comment by davidchambers** [comment]
I was just about to open a pull request to add __bower.json__, but encountered a hitch:

```console
$ bower info string-format
bower string-format#*           cached https://github.com/jsoverson/string-format.git#1.0.2
bower string-format#*         validate 1.0.2 against https://github.com/jsoverson/string-format.git#*

{
  name: 'string-format',
  main: 'string-format.js',
  version: '1.0.2',
  homepage: 'https://github.com/jsoverson/string-format'
}

Available versions:
  - 1.0.2
  - 1.0.1
  - 0.6.1
You can request info for a specific version with 'bower info string-format#<version>'
```

We have two options, I think:

  - choose a different name (`bower search string-format` currently returns 11 results); or
  - ask the author of the existing `string-format` to consider making the name available to us.

**Comment by davidchambers** [comment]
[Bower][1] is being retired, so I'll close this issue.


[1]: https://bower.io/
