### ISSUE TITLE
Can't find the format-string.js file

### ISSUE THREAD

**Issue by math2001** [davidchambers/string-format#21]
I feel a bit stupid right now, but I can't find the `format-string.js` file, or any that would do the job...

**Comment by davidchambers** [comment]
The file is named __index.js__. :)

**Comment by math2001** [comment]
:disappointed: I tried this file, but I then used the `.format` which is not defined, so i though it was the wrong one... After reading the readme properly, i realised it was not defined by default... Sorry...

**Comment by davidchambers** [comment]
No problem at all. :)
