### ISSUE TITLE
Update description in npm

### ISSUE THREAD

**Issue by mjomble** [davidchambers/string-format#22]
The description of the npm package still mentions "Adds a format method to String.prototype.", based on older default behavior.
It should now probably make it clearer that this is optional and not enabled by default.

**Comment by davidchambers** [comment]
Good point, @mjomble. The `description` field in __package.json__ has actually been updated, but we have not published to npm since making that change. I should release v0.6.0.

**Comment by davidchambers** [comment]
```console
$ npm view string-format@1.0.0 description
String formatting inspired by Python's str.format()
```

I'm sorry this took so long!
