### ISSUE TITLE
Get null or undefined to print as string 'null' or 'undefined' rather than as empty string.

### ISSUE THREAD

**Issue by RobPethick** [davidchambers/string-format#35]
Hi -
I have a dependency on your library in mine https://github.com/RobPethick/jest-theories - I was wondering what the recommended way would be to get null or undefined to print as 'null' or 'undefined' rather than printing as empty string? Is it possible with a format.extend?

**Comment by RobPethick** [comment]
@davidchambers looks like you fixed this in the commit you've referenced - has this been re-released to NPM since?

**Comment by davidchambers** [comment]
@RobPethick, a new version is now available from the npm registry:

```console
$ npm view string-format version
2.0.0
```
