### ISSUE TITLE
ES6：模板字符串 ?

### ISSUE THREAD

**Issue by xingzhefeng** [davidchambers/string-format#38]
https://www.jianshu.com/p/8b263a6bde4d

**Comment by davidchambers** [comment]
Are you suggesting that [template literals][1] make this library unnecessary, @xingzhefeng? If so, I agree. I would not have created this library in 2018, but it made sense in 2012.


[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
