### ISSUE TITLE
Multiple transformers per placeholder

### ISSUE THREAD

**Issue by nombrekeff** [davidchambers/string-format#41]
Hi, I dont know if this can be done, but I could not find a solution so far.

I was wondering if its posible to have multiple transformers per placeholder, for example:
```js
format(`{time!date!lbl_cyan}`, log);
```
> ValueError: no transformer named "date,lbl_cyan"
>     at ValueError (C:\Users\keff\Desktop\cosas\Dev\LibsJS\loggin-js\node_modules\string-format\index.js:7:15)

It would be cool to be able to concatenate transformers in some way.

Cheers!

**Comment by davidchambers** [comment]
We follow Python's lead where possible. Python's [format string syntax][1] permits at most one conversion (transformer) per placeholder. I suggest using template literals:

```javascript
> let s = '0x6E4'

> `The square root of ${s} is ${Math.sqrt (parseInt (s))}`
'The square root of 0x6E4 is 42'
```


[1]: https://docs.python.org/2/library/string.html#format-string-syntax

**Comment by nombrekeff** [comment]
Ohh okay I understand! 
I will make my own implementation based on yours!
Keep the good work!
Cheers!

**Comment by davidchambers** [comment]
> I will make my own implementation based on yours!

Excellent. It's nice to be able to fork a project to scratch an itch. :)

**Comment by nombrekeff** [comment]
Yeah, It's quite nice!
I did a bit more that add multiple transformers in the end :P
Check it out if you'd like:  https://github.com/nombrekeff/strif

**Comment by davidchambers** [comment]
Bravo, Manolo! :clap:
