### ISSUE TITLE
Support String.prototype.substring

### ISSUE THREAD

**Issue by aeneal** [davidchambers/string-format#50]
Hi, 
I don't have any super advanced use cases but I can't seem to find support for substring,

eg:

 "I've always wanted to go to a goth club. {quip.substring(1,4)}".format (sheldon)
"I've always wanted to go to a goth club. BAZ"

**Comment by davidchambers** [comment]
@aeneal, is using [template literals][1] an option for you?

```javascript
> `I've always wanted to go to a goth club. ${sheldon.quip().slice(0, 3).toUpperCase()}!`
"I've always wanted to go to a goth club. BAZ!"
```


[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
