### ISSUE TITLE
How Can I load the library using AMD style ? 

### ISSUE THREAD

**Issue by nadeemkhoury** [davidchambers/string-format#51]
Hi, 
I tried to use the library using the AMD style. 
I uploaded the index,js in my Modules Folder, and I included the path in my define method as following: 
```

define(['Modules/index.js'],
    function (index) { } );
```

But it is not working at all. 
Can you please explain or guide me how to load it ? 
Note; I'm using Suitescript, it is framework for Netsuite ERP system. It uses the RequireJs to handle the module loading. In order to load a module in suitescript, it must be AMD-Formatted. 
Is the library AMD-Formatted or I'm doing something wrong ? 
Any help or explanation would be so much appreciated,

**Comment by davidchambers** [comment]
The library is not currently compatible with AMD. I could add support for AMD, but I cannot make a promise as to when I will have time to do so.

**Comment by nadeemkhoury** [comment]
Thank You david or your quick response. 
Actually, I'm not experienced in Javascript world. But when I looked into the code inside index.js I found this piece of code: 
```
if (typeof module !== 'undefined') {
    module.exports = format;
  } else if (typeof define === 'function' && define.amd) {
    define (function() { return format; });
  } else {
    global.format = format;
  }
```
I expected that it is compatible with AMD. Can you please just tell me what is that code for  ? 

Thank you so much.

**Comment by davidchambers** [comment]
You are quite right, Nadeem. Please share the results of evaluating the following expressions in your environment:

  - `typeof module`
  - `typeof define`
  - `typeof define === 'function' && define.amd`
