### ISSUE TITLE
Current version on NPM (0.2.1) doesn't export anything

### ISSUE THREAD

**Issue by guncha** [davidchambers/string-format#7]
Trying to get it working with Browserify and it would be great if the module would export the `format` function. It's on the master, I guess the package just hasn't been updated in a while.

**Comment by davidchambers** [comment]
Thanks for encouraging me to finish the documentation changes in #6 in order to merge that pull request and publish a new version. 0.5.0 is now available on GitHub and npm. :)

**Comment by guncha** [comment]
Sweet, thanks, David! :+1:
